import {
  StarRate,
  Face,
  CheckCircleOutline,
  ThumbUp,
  ThumbUpRounded,
  GroupSharp,
  EmojiEvents,
} from '@material-ui/icons';

export const lines = [
  {
    id: '1',
    title: '中国DevOps社区',
    date: '2020',
    imageSrc: 'image/devops2020.jpg',
    description: '2020年度中国DevOps社区志愿者',
    icon: ThumbUp,
  },
  {
    id: '2',
    title: 'HDZ',
    date: '2020',
    imageSrc: 'image/hdz.jpg',
    description: '2020年在华为云HDZ正式转正',
    icon: ThumbUpRounded,
  },
  {
    id: '3',
    title: 'HDZ贡献领袖',
    date: '2020',
    imageSrc: 'image/hdz2020gx.jpg',
    description: '被授予2020年度华为云HDZ社区贡献领袖奖',
    icon: EmojiEvents,
  },
  {
    id: '4',
    title: 'ACE',
    date: '2021',
    imageSrc: 'image/ace.jpg',
    description: '在阿里云ACE正式转正',
    icon: Face,
  },
  {
    id: '5',
    title: '中国DevOps社区',
    date: '2021',
    imageSrc: 'image/devops2021.jpg',
    description: '2021年度中国DevOps社区志愿者',
    icon: CheckCircleOutline,
  },
  {
    id: '6',
    title: "COSCon'21",
    date: '2021',
    imageSrc: 'image/concon21.jpg',
    description: "开源社COSCon'21志愿者",
    icon: StarRate,
  },
  {
    id: '7',
    title: 'COSCon之星',
    date: '2021',
    imageSrc: 'image/conconzx.jpg',
    description: '被授予COSCon中国开源年会『COSCon之星』',
    icon: EmojiEvents,
  },
  {
    id: '8',
    title: '云享专家',
    date: '2021',
    imageSrc: 'image/yxzj.jpg',
    description: '正式授予云享专家证书',
    icon: Face,
  },
  {
    id: '9',
    title: 'HDZ卓越领袖',
    date: '2021',
    imageSrc: 'image/hdz2021zy.jpg',
    description: '被授予2021年度华为云HDZ社区卓越领袖奖',
    icon: EmojiEvents,
  },
  {
    id: '10',
    title: '社区之光',
    date: '2022',
    imageSrc: 'image/sqzg.jpg',
    description: '被授予社区之光奖',
    icon: EmojiEvents,
  },
];
