/** Declaration file generated by dts-gen */
declare module 'react-vertical-timeline-component' {
  export function VerticalTimeline({
    animate,
    className,
    layout,
    lineColor,
    children,
  }: any): any;

  export function VerticalTimelineElement({
    children,
    className,
    contentArrowStyle,
    contentStyle,
    date,
    dateClassName,
    icon,
    iconClassName,
    iconOnClick,
    onTimelineElementClick,
    iconStyle,
    id,
    position,
    style,
    textClassName,
    intersectionObserverProps,
    visible,
  }: any): any;

  export namespace VerticalTimeline {
    const defaultProps: {
      animate: boolean;
      className: string;
      layout: string;
      lineColor: string;
    };

    namespace propTypes {
      function animate(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function children(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function className(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function layout(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function lineColor(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      namespace animate {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace className {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace layout {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace lineColor {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }
    }
  }

  export namespace VerticalTimelineElement {
    const defaultProps: {
      children: string;
      className: string;
      contentArrowStyle: any;
      contentStyle: any;
      date: string;
      dateClassName: string;
      icon: any;
      iconClassName: string;
      iconOnClick: any;
      iconStyle: any;
      id: string;
      intersectionObserverProps: {
        rootMargin: string;
        triggerOnce: boolean;
      };
      onTimelineElementClick: any;
      position: string;
      style: any;
      textClassName: string;
      visible: boolean;
    };

    namespace propTypes {
      function children(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function className(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function contentArrowStyle(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function contentStyle(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function date(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

      function dateClassName(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function icon(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

      function iconClassName(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function iconOnClick(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function iconStyle(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function id(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

      function intersectionObserverProps(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function onTimelineElementClick(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function position(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function style(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

      function textClassName(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      function visible(
        p0: any,
        p1: any,
        p2: any,
        p3: any,
        p4: any,
        p5: any,
      ): any;

      namespace children {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace className {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace contentArrowStyle {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace contentStyle {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace date {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace dateClassName {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace icon {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace iconClassName {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace iconOnClick {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace iconStyle {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace id {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace intersectionObserverProps {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace onTimelineElementClick {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace position {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace style {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace textClassName {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }

      namespace visible {
        function isRequired(
          p0: any,
          p1: any,
          p2: any,
          p3: any,
          p4: any,
          p5: any,
        ): any;
      }
    }
  }
}
